#!/bin/sh

# SPDX-FileCopyrightText: 2021 GNOME Foundation
#                         2024 Colin Kiama
#
# SPDX-License-Identifier: CC0-1.0

sourcedir="source"
builddir="build"

SPHINX_BUILD="sphinx-build"

[ type -a ${SPHINX_BUILD} ] || {
        echo "Missing ${SPHINX_BUILD} in PATH; have you installed Sphinx?"; exit 2;
}

if [ "$1" != "--incremental" ]; then
	[ -d "${builddir}" ] && rm -rf "${builddir}"
	mkdir "${builddir}"
fi

${SPHINX_BUILD} ${SPHINXOPTS} "${sourcedir}" "${builddir}" || exit $?

