name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: ["Feature Request"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to give us new ideas!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Please describe what you want added.
      placeholder: Guide on how to use if statements
    validations:
      required: true
  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible Solutions
      description: What might be some possible solutions to this problem?
      placeholder: The following article shows one solution https:// ...
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Please provide anything else that might be helpful, including screenshots, article links, link to existing implementations, etc.
    validations:
      required: false